version: "3"

services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=r2m2m
      - POSTGRES_PASSWORD=r2m2m
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5